services:
  # Backend (NestJS)
  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: atenea_backend
    ports:
      - "3000:3000"
    networks:
      - atenea_network
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://root:123@db:5432/atenea"

  # PostgreSQL Database
  db:
    image: postgres:17
    container_name: atenea_db
    environment:
      POSTGRES_USER: atenea_user
      POSTGRES_PASSWORD: atenea_pass
      POSTGRES_DB: atenea_db
    ports:
      - "5432:5432"
    networks:
      - atenea_network
    restart: unless-stopped

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: atenea_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - atenea_network

networks:
  atenea_network:
    driver: bridge