services:
  - type: web
    name: atenea-backend
    env: node
    buildCommand: npm ci && npm install && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
        -key: PORT 
        value: '10000'
    ipAllowList: []