services:
  - type: web
    name: atenea-backend
    env: node
    buildCommand: npm ci && npm install && npm run build
    startCommand: npx prisma db push --accept-data-loss && npm run start:prod
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '10000'
      - key: DATABASE_URL
        fromDatabase:
          name: atenea-db
          property: connectionString
    ipAllowList: []